# Generated by Django 5.2.4 on 2025-07-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace del producto'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='places', verbose_name='Imagen'),
        ),
    ]
