# Generated by Django 5.2.4 on 2025-07-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_url_alter_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número con código de país (ej: 593987654321)', max_length=20, null=True, verbose_name='Número WhatsApp'),
        ),
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace dirección'),
        ),
    ]
