# Generated by Django 5.2.4 on 2025-07-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_whatsapp_number_alter_place_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='menu_file',
            field=models.FileField(blank=True, help_text='Sube un PDF o imagen del menú del lugar', null=True, upload_to='places/menus', verbose_name='Menú (PDF/Imagen)'),
        ),
    ]
