# Generated by Django 5.2.4 on 2025-08-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitcounter_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitcounter',
            options={'verbose_name': 'visita', 'verbose_name_plural': 'visitas'},
        ),
    ]
