# Generated by Django 5.2.4 on 2025-07-11 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('excerpt', models.TextField(help_text='Resumen corto del artículo', max_length=300, verbose_name='Extracto')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Imagen')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Entrada de Blog',
                'verbose_name_plural': 'Entradas de Blog',
                'ordering': ['-published_date', '-created_date'],
            },
        ),
    ]
