# Generated by Django 5.2.4 on 2025-07-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='url',
            field=models.URLField(blank=True, help_text='URL completa del artículo (ej: https://ejemplo.com/articulo)', null=True, verbose_name='Enlace para leer más'),
        ),
    ]
